name: Security Audit
on: [push, pull_request]

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Set Composer Cache Directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.3-composer-

      - name: Update Composer
        run: composer self-update

      - name: Install Dependencies
        run: composer install --no-progress --optimize-autoloader --prefer-dist --no-interaction

      - name: Run Security Audit
        run: |
          composer audit \
            --format=json \
            --ignore-severity=low \
            --ignore-severity=medium \
            --no-ansi \
            --no-dev \
            --no-abandoned=report \
            > /tmp/security-audit.json

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit
          path: /tmp/security-audit.json